POST  http://localhost:8080/login
Content-Type: application/json

{
    "email" : "ac@a",
    "password": "aca"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "ac@a",
    "password": "aca"
}

###
GET http://localhost:8080/assignment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI2ODM0Mzl9.KAN7J9ZQ5Q6q8b37Mwoz5GN09ITwaN6ZS0EFm0Ea4PY

###
GET http://localhost:8080/course
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI2Mzc3Mjh9.FRm9s5Y3AZ9atN9pBO2bmewk5bvPaQkE0JDX6txaYvs

###
GET http://localhost:8080/presence/date/2023-12-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI2Mzg5NDV9.Ujf_DwDOfWAJFEzU95UnT0jA4poO_MuthPv-NB-NO1w

###
###
GET http://localhost:8080/course
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI2MzgyODh9.eNml0DQvUzyCF67PaDCG-L-iJCb35SHOuBoSTzqyMj8

###
GET http://localhost:8080/get-student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI2MzgyODh9.eNml0DQvUzyCF67PaDCG-L-iJCb35SHOuBoSTzqyMj8

{
    "studentId": "gEaUjV3Q",
    "courseId": "5AFo0SrdoL"
}