POST  http://localhost:8080/login
Content-Type: application/json

{
    "email" : "salsa@gmail.com",
    "password": "salsa"
}

###
POST  http://localhost:8080/login
Content-Type: application/json

{
    "email" : "ac@a",
    "password": "aca"
}



###
GET http://localhost:8080/assignment/student/00WnXgyH/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMHF6UTZybzkiLCJlbWFpbCI6InNhbHNhQGdtYWlsLmNvbSIsImlhdCI6MTcwMjgwOTk4NH0.f8HuWdKKDFonbMjyucZO3FAuR0wLbHmAKZ9ULZTVoHw

###
GET http://localhost:8080/course
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMHF6UTZybzkiLCJlbWFpbCI6InNhbHNhQGdtYWlsLmNvbSIsImlhdCI6MTcwMjgwOTk4NH0.f8HuWdKKDFonbMjyucZO3FAuR0wLbHmAKZ9ULZTVoHw
###
GET http://localhost:8080/presence/date/2023-12-20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI3OTYxODd9.HxPLAVP5GsKEHZ6ylXuDvPPC3EWulSVenHDmGwEwdlQ

###
GET http://localhost:8080/course
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI3OTYxODd9.HxPLAVP5GsKEHZ6ylXuDvPPC3EWulSVenHDmGwEwdlQ
###
###
GET http://localhost:8080/get-student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI3OTYxODd9.HxPLAVP5GsKEHZ6ylXuDvPPC3EWulSVenHDmGwEwdlQ

###
GET http://localhost:8080/get-student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNFZVZXA0eDAiLCJlbWFpbCI6ImFjQGEiLCJpYXQiOjE3MDI3OTYxODd9.HxPLAVP5GsKEHZ6ylXuDvPPC3EWulSVenHDmGwEwdlQ

{
    "studentId": "gEaUjV3Q",
    "courseId": "5AFo0SrdoL"
}
